### PR TITLE
Allow 'limit', 'skip' and 'sort' in query params

### PR DESCRIPTION
**Pull request by tomaash**
The get query can now look like this: 
http://localhost:8080/api/cars?conditions={"brand":"ford"}&limit=10&skip=1&sort=-brand

### CODE REVIEW

**Comment by t3chnoboy** [comment]
Awesome! Thank you! :+1:

**Comment by tomaash** [comment]
Thanks for merging this so quickly. Just mind that this is a breaking change - querying find conditions before was /api?attr=value, now is /api?conditions={"attr":"value"}

**Comment by t3chnoboy** [comment]
Oh. I've published it as 0.3.0
We need to update the docs and republish it as 1.0.0
What do you think?

**Comment by t3chnoboy** [comment]
Also, would you mind if I add you to the repo?

**Comment by tomaash** [comment]
OK, count me in. Will you update the docs, or should I do it?

**Comment by t3chnoboy** [comment]
If you feel like it then go for it.
Anyway, thanks a lot for your help and contribution! :smile:

**Comment by tomaash** [comment]
OK, it's there. Also, for one small breaking change 0.2.0 => 0.3.0 should be enough.

**Comment by t3chnoboy** [comment]
Great! Thanks!

**Comment by tomaash** [comment]
I updated dependencies, fixed failing test and bumped version to 0.3.1. Can you please publish to npm? Thanks..

**Comment by t3chnoboy** [comment]
Awesome! I've just published the new version.

**Comment by t3chnoboy** [comment]
I'll try to give you access to the npm package

**Comment by t3chnoboy** [comment]
What's your npm username?

**Comment by tomaash** [comment]
tomaash as well :)

**Comment by t3chnoboy** [comment]
Just added you on npm. Can you check, please?

**Comment by tomaash** [comment]
It's there. Thanks. Just for you to know about my motivation, I like to use https://github.com/wprl/baucis, but it does not support Koa. Your library albeit really simple already fills most of the basic needs, so we'll see, how far we can get with this ;)

**Comment by t3chnoboy** [comment]
Sounds great! Feel free to ask if you need any help :smile:

**Comment by mgenev** [comment]
I've also adopted this library in my project here https://github.com/mgenev/nautilus and I'll be making further pull requests.

**Comment by t3chnoboy** [comment]
@mgenev awesome! Thank you for your pull request! Sorry for the late reply, I have finals this week so I was very busy. I appreciate your help! If you are going to contribute to this project I can add you as a collaborator. Are you ok with that?

**Comment by mgenev** [comment]
Yes, I'd be happy, thank you :)

**Comment by t3chnoboy** [comment]
Done! I'll also add you on npm

**Comment by t3chnoboy** [comment]
What's your npm username?

**Comment by mgenev** [comment]
same as here `mgenev`

**Comment by t3chnoboy** [comment]
just added you. Can you check, please?

**Comment by mgenev** [comment]
yep it came through, exciting

**Comment by mgenev** [comment]
why is there an empty folder /models btw?

**Comment by t3chnoboy** [comment]
we should remove that. It was used in previous versions.

**Pull request merged**
